#!/usr/bin/env python3
"""Compute every number that appears in the paper text.

Outputs paper/part1/auto_numbers.tex with LaTeX macros.
Every number in the paper must come from these macros.
"""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
import numpy as np, pandas as pd
from sklearn.decomposition import PCA

EXPECTED_MODELS = [
    "Qwen/Qwen2.5-7B-Instruct",
    "meta-llama/Llama-3.1-8B-Instruct",
    "mistralai/Mistral-7B-Instruct-v0.3",
]
MODEL_SHORT = {
    "Qwen/Qwen2.5-7B-Instruct": "Qwen",
    "meta-llama/Llama-3.1-8B-Instruct": "Llama",
    "mistralai/Mistral-7B-Instruct-v0.3": "Mistral",
}
MODEL_LAYERS = {"Qwen/Qwen2.5-7B-Instruct": 28, "meta-llama/Llama-3.1-8B-Instruct": 32, "mistralai/Mistral-7B-Instruct-v0.3": 32}

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--core-parquet", type=Path, default=Path("paper/part1/data/part1_core.parquet"))
    ap.add_argument("--output", type=Path, default=Path("paper/part1/auto_numbers.tex"))
    args = ap.parse_args()

    core = pd.read_parquet(args.core_parquet)
    pl = core.groupby(["model_id", "prompt_uid"]).first().reset_index()
    macros = {}

    # Global counts
    macros["NModels"] = len(core["model_id"].unique())
    macros["NPromptsPerModel"] = 3000
    macros["NPromptsTotal"] = int(pl.shape[0])
    macros["NRowsCore"] = len(core)
    macros["TauDefault"] = "1.0"
    macros["MDefault"] = "0.75"
    macros["MaxFlips"] = 1
    macros["Seed"] = 12345

    # Per-model stats
    for m in EXPECTED_MODELS:
        short = MODEL_SHORT[m]
        sub = pl[pl["model_id"] == m]
        L = MODEL_LAYERS[m]
        macros[f"NLayers{short}"] = L

        for regime in ["Stable-Correct", "Stable-Wrong", "Unstable"]:
            tag = regime.replace("-", "").replace(" ", "")
            rsub = sub[sub["regime"] == regime]
            n = len(rsub)
            pct = 100.0 * n / len(sub)
            med = float(rsub["final_delta_default"].median()) if n > 0 else 0.0
            macros[f"N{tag}{short}"] = n
            macros[f"Pct{tag}{short}"] = f"{pct:.1f}"
            macros[f"MedDelta{tag}{short}"] = f"{med:+.2f}"

        # Commitment depth
        committed = sub[sub["commitment_layer"].notna()]
        if len(committed) > 0:
            depths = committed["commitment_layer"].values / (L - 1)
            macros[f"CommitMeanDepth{short}"] = f"{depths.mean():.2f}"
            macros[f"CommitMedDepth{short}"] = f"{np.median(depths):.2f}"
        macros[f"MeanFlipCount{short}"] = f"{sub['flip_count'].mean():.2f}"

        # PCA
        sub_all = core[core["model_id"] == m]
        X = sub_all[["sA", "sB", "sC", "sD"]].values
        pca = PCA(n_components=2, random_state=12345)
        pca.fit(X)
        macros[f"PCAOneVar{short}"] = f"{100*pca.explained_variance_ratio_[0]:.1f}"
        macros[f"PCATwoVar{short}"] = f"{100*pca.explained_variance_ratio_[1]:.1f}"
        macros[f"PCATotalVar{short}"] = f"{100*sum(pca.explained_variance_ratio_):.1f}"

    # Switch-induced jump statistics
    switch_rows = core[core["switch_indicator"] == 1].copy()
    if len(switch_rows) > 0:
        # Compute delta_hard jump at switch layers
        jumps_hard = []
        jumps_soft = []
        for (mid, puid), grp in core.groupby(["model_id", "prompt_uid"]):
            grp = grp.sort_values("layer_index")
            sw = grp["switch_indicator"].values
            dh = grp["delta_hard_dyn"].values
            ds = grp["delta_default"].values
            for i in range(1, len(sw)):
                if sw[i] == 1:
                    jumps_hard.append(abs(dh[i] - dh[i-1]))
                    jumps_soft.append(abs(ds[i] - ds[i-1]))
        macros["NSwitchEvents"] = len(jumps_hard)
        macros["MeanJumpHard"] = f"{np.mean(jumps_hard):.2f}"
        macros["MedJumpHard"] = f"{np.median(jumps_hard):.2f}"
        macros["MeanJumpSoft"] = f"{np.mean(jumps_soft):.2f}"
        macros["MedJumpSoft"] = f"{np.median(jumps_soft):.2f}"
        macros["JumpReductionPct"] = f"{100*(1 - np.mean(jumps_soft)/np.mean(jumps_hard)):.0f}"

    # Smoothness metric for robustness
    # (computed during figure generation, placeholder here)
    macros["RobustnessMaxShift"] = "---"

    # Write LaTeX macros
    lines = ["%% Auto-generated by compute_numbers.py — DO NOT EDIT\n"]
    for k, v in sorted(macros.items()):
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))
    print(f"Wrote {len(macros)} macros to {args.output}")

    # Also write JSON for quality gates
    json_path = args.output.with_suffix(".json")
    json_path.write_text(json.dumps(macros, indent=2, default=str) + "\n")
    print(f"Wrote JSON to {json_path}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
